### ISSUE TITLE
リリース

### ISSUE THREAD

**Issue by Aguri** [touyou/CheckItOut#1]
ダウンロードしたい！

**Comment by touyou** [comment]
リリースまでの最低限のTO-DO

- [x] Autolayoutを適用する。iPadまで対応できるよう配置出来ると完璧。
- [ ] リリースのためのアセット用意。ひとまずチュートリアルは後々入れることにしてまずはスクショで使い方を説明する。
- [x] デフォルト音源の扱いをどうするのか決める。デバッグ専用にするのか、ある程度は残しておくのか。あとは命名など。
- [x] 表示を日本語名、保存をハッシュ値にする。関連して状態を保存しておけるようにしておく。

**Comment by Aguri** [comment]
@touyou 
おｋスクショは俺用意するね！
ipadで出来るとすごくいいね、画面でかいし楽器感すごいあると思う！

音源の扱い悩むねｗ
最初からある程度アサインしておく方が最初に触ったとき音出て楽しいと思う。

あと今ひらがなでファイル名付けられないもの問題だと思っていて、表示名（ユーザーが付ける）とファイル名（こちらで一意のハッシュ値など）でファイルを保存しておいて、音を呼び出す時はファイル名を使う感じとかどうだろ？

**Comment by touyou** [comment]
@Aguri たしかにファイル名そうですね！もしかしたら日本語ファイル名も大丈夫かもしれないですが…一応日付からのハッシュ値で保存されるようにしてみます！

**Comment by Aguri** [comment]
タイトルと背景！

[UIConponents2.1.zip](https://github.com/touyou/CheckItOut/files/798582/UIConponents2.1.zip)

**Comment by touyou** [comment]
![img_2494](https://cloud.githubusercontent.com/assets/465697/23300753/5b1e95e8-faca-11e6-8ee0-fe47aa3cf277.PNG)
![img_2495](https://cloud.githubusercontent.com/assets/465697/23300752/5b19795a-faca-11e6-9b21-f0768898ed57.JPG)

ボタンへの画像の適用の仕方のせいで縦と横のマージンをうまくデバイス間で統一することができないなぁ...

**Comment by touyou** [comment]
さっきの問題投稿した直後にアスペクト比で指定すればいいやんって当たり前のことに気付いて直せた、done

**Comment by touyou** [comment]
MEMO 日本語名でも保存できるが、読み出す時に日本語として表示されなくなる

**Comment by Aguri** [comment]
@touyou 
申請用のスクショ、明日中にあげるわ！チェケラな感じなの作る！
読み出すと日本語使えないの謎だねｗ

**Comment by touyou** [comment]
@Aguri あざます！
日本語で表示されないっていうのはURLに日本語がはいってた時とおんなじ形式になる感じです（多分表示するときにutf-8とかになおしてやれば直るかも）

ただどっちにしろ一回設定したらアプリ閉じても戻すようにする時にデータ保存とか色々しなきゃいけないのでそれと一緒にファイル名と表示名わけるのがよさそうです。

**Comment by touyou** [comment]
### 保存するモデル

- 表示名
- url
- 割り当てられているPAD番号

### 現状の管理方法

- players ... ボタン一個に対するAudioPlayer
- selectedUrl ... i番目にi番のPADに割り当てられているもののURL
- mapToNumber ... absoluteStringに対して何番のPADに割り当てられているかを辞書で管理している
- fileUrl ... 全URLリスト

### 移行案

- playersはそのまま
- 一回ごとlsするのはやめてファイルはDocumentのまま他のデータはRealmのオブジェクトに統一する
- selectedUrlは現状のまま
- mapToNumberはRealmのプライマリキーをurlかurlのabsoluteStringにしておけば代用可能なはず
- fileUrlはRealmにまかせるため廃止

### 進捗

- [x] モデル作成
- [x] 移行作業
- [x] デフォルトの音源を適切な場所に移動

**Comment by Aguri** [comment]
![white - white - tilted bottom](https://cloud.githubusercontent.com/assets/7918776/23332925/396f7c72-fbc5-11e6-8253-c2c7a14d4f82.png)
![white - white - tilted top](https://cloud.githubusercontent.com/assets/7918776/23332926/39d1f906-fbc5-11e6-9d4b-e8ed7abfc4b8.png)


左上に文字どんなアプリか説明する文字いれたい！
もうちょい練るわ！

**Comment by touyou** [comment]
今professionalってやつ表示されてないです😅

**Comment by touyou** [comment]
- Bundleのパスが一意じゃないから保存と実体が異なってくる→ファイル名だけにする？
- 追加したあとリロードのタイミングが悪い。

**Comment by touyou** [comment]
上の問題done
あとでpushする

**Comment by touyou** [comment]
- バスドラ、みんなで、チェケラをデフォルトでアサイン

**Comment by Aguri** [comment]
@touyou スクショあげるので少々お待ちを！
素材あれば申請できる？

**Comment by Aguri** [comment]
[スクショ.zip](https://github.com/touyou/CheckItOut/files/810024/default.zip)

**Comment by Aguri** [comment]
http://qiita.com/mono0926/items/0b1122e5a254f945f6b0
ここに書いてあるサイズでスクショ画面書きだしたけど、これでいけるかな？

**Comment by Aguri** [comment]
[IpadScreenshots.zip](https://github.com/touyou/CheckItOut/files/813079/IpadScreenshots.zip)
とりいそぎ！

**Comment by touyou** [comment]
リリースﾄﾞﾈ！
